# Generated by Django 3.2.6 on 2021-11-02 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TanqueCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('terminal', models.CharField(default='CARTAGENA', max_length=20)),
                ('tipo', models.CharField(max_length=150)),
                ('diametro', models.FloatField(max_length=6, verbose_name='Diámetro')),
                ('altura_cilindro', models.FloatField(max_length=6)),
                ('altura_medicion', models.FloatField(max_length=6, verbose_name='Altura medición')),
                ('fecha_aforo', models.DateField()),
                ('norma', models.CharField(max_length=150)),
                ('volumen', models.FloatField(blank=True, max_length=8, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='LoteCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('referencia', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=25)),
                ('temperatura_ref', models.FloatField(blank=True, max_length=4, null=True)),
                ('densidad_ref', models.FloatField(blank=True, max_length=6, null=True)),
                ('factor_correccion', models.FloatField(blank=True, max_length=6, null=True, verbose_name='Factor corrección')),
                ('nombre_buque', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_llegada_buque', models.DateField(blank=True, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='CalculoCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('estado', models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA')], max_length=2)),
                ('medicion', models.FloatField(blank=True, default=0, max_length=7, null=True, verbose_name='Medición')),
                ('tabla_6d', models.FloatField(blank=True, default=0, max_length=8, null=True)),
                ('tabla_13', models.FloatField(blank=True, default=0, max_length=8, null=True)),
                ('volumen', models.FloatField(blank=True, max_length=8, null=True)),
                ('temperatura_tq', models.FloatField(blank=True, max_length=4, null=True)),
                ('sellos_valvulas', models.CharField(blank=True, max_length=150, verbose_name='Sellos Válvulas')),
                ('sellos_tapas', models.CharField(blank=True, max_length=150)),
                ('densidad', models.FloatField(blank=True, default=0, max_length=8, null=True)),
                ('masa', models.FloatField(blank=True, max_length=8, null=True)),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='ctg.lotectg')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanque', to='ctg.tanquectg')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AforoTanqueCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('medicion', models.FloatField(blank=True, max_length=7, null=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctg.tanquectg')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
        ),
    ]
