# Generated by Django 4.0.2 on 2022-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanquectg',
            name='bodega',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
