# Generated by Django 4.0.2 on 2022-03-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctg', '0005_alter_tanquectg_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteApiCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('referencia', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=25)),
                ('temperatura', models.FloatField(max_length=4)),
                ('api', models.FloatField(max_length=4)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='CalculoApiCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('medicion', models.FloatField(default=0, max_length=7, verbose_name='Medición')),
                ('tabla_6d', models.FloatField(max_length=7)),
                ('volumen', models.FloatField(blank=True, max_length=8, null=True)),
                ('masa', models.FloatField(blank=True, max_length=8, null=True)),
                ('estado', models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA')], max_length=2)),
                ('temperatura_tq', models.FloatField(blank=True, max_length=4, null=True)),
                ('densidad', models.FloatField(blank=True, default=0, max_length=8, null=True)),
                ('lote_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_api', to='ctg.loteapictg')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctg.tanquectg')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
