# Generated by Django 4.0.2 on 2022-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctg', '0007_loteapictg_cliente_lotectg_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculoapictg',
            old_name='lote_api',
            new_name='lote',
        ),
        migrations.AlterField(
            model_name='calculoapictg',
            name='estado',
            field=models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA'), ('ID', 'INICIAL DESPACHO'), ('IR', 'INICIAL RECIBO'), ('FD', 'FINAL DESPACHO'), ('FR', 'FINAL RECIBO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='calculoctg',
            name='estado',
            field=models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA'), ('ID', 'INICIAL DESPACHO'), ('IR', 'INICIAL RECIBO'), ('FD', 'FINAL DESPACHO'), ('FR', 'FINAL RECIBO')], max_length=2),
        ),
    ]
