# Generated by Django 4.0.2 on 2022-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctg', '0008_rename_lote_api_calculoapictg_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoapictg',
            name='do',
            field=models.IntegerField(blank=True, null=True, verbose_name='DO'),
        ),
        migrations.AddField(
            model_name='calculoctg',
            name='do',
            field=models.IntegerField(blank=True, null=True, verbose_name='DO'),
        ),
    ]
