# Generated by Django 3.2.6 on 2021-09-06 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculo',
            name='densidad_ref',
        ),
        migrations.RemoveField(
            model_name='calculo',
            name='factor_correccion',
        ),
        migrations.RemoveField(
            model_name='calculo',
            name='temperatura_ref',
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('referncia', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=25)),
                ('temperatura_ref', models.FloatField(blank=True, max_length=4, null=True)),
                ('densidad_ref', models.FloatField(blank=True, max_length=6, null=True)),
                ('factor_correccion', models.FloatField(blank=True, max_length=6, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
