# Generated by Django 3.2.6 on 2021-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0004_alter_lote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='volumen',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
    ]
