# Generated by Django 3.2.6 on 2021-09-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0005_tanque_volumen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanque',
            options={'ordering': ['-creado']},
        ),
    ]
