# Generated by Django 3.2.6 on 2021-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0006_alter_tanque_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='estado',
            field=models.CharField(choices=[('F', 'Final'), ('I', 'Inicial'), ('C', 'Control'), ('D', 'Definitiva')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
