# Generated by Django 3.2.6 on 2021-09-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0008_auto_20210923_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aforotanque',
            old_name='milimetros',
            new_name='medicion',
        ),
        migrations.AlterField(
            model_name='calculo',
            name='medicion',
            field=models.FloatField(blank=True, max_length=7, null=True, verbose_name='Medición'),
        ),
    ]
