# Generated by Django 3.2.6 on 2021-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0009_auto_20210923_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fecha_llegada_buque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='nombre_buque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='factor_correccion',
            field=models.FloatField(blank=True, max_length=6, null=True, verbose_name='Factor corrección'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='altura_medicion',
            field=models.FloatField(max_length=6, verbose_name='Altura medición'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='diametro',
            field=models.FloatField(max_length=6, verbose_name='Diámetro'),
        ),
    ]
