# Generated by Django 3.2.6 on 2021-10-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0011_auto_20210929_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='estado',
            field=models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='calculo',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='bun.lote'),
        ),
    ]
