# Generated by Django 3.2.6 on 2021-10-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0012_auto_20211026_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanque', to='bun.tanque'),
        ),
    ]
