# Generated by Django 3.2.6 on 2021-10-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0013_alter_calculo_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='bun.lote'),
        ),
    ]
