# Generated by Django 3.2.6 on 2021-10-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0014_alter_calculo_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='api',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='tabla_13',
            field=models.FloatField(blank=True, default=0, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='tabla_6d',
            field=models.FloatField(blank=True, default=0, max_length=8, null=True),
        ),
    ]
