# Generated by Django 3.2.6 on 2021-10-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0015_auto_20211028_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='densidad',
            field=models.FloatField(blank=True, default=0, max_length=8, null=True),
        ),
    ]
