# Generated by Django 3.2.6 on 2021-10-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0017_alter_calculo_medicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculo',
            name='api',
        ),
    ]
