# Generated by Django 3.2.6 on 2021-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0018_remove_calculo_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='terminal',
            field=models.CharField(default='BUENAVENTURA', max_length=20),
        ),
    ]
