# Generated by Django 4.0.2 on 2022-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0021_calculopruebas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='bodega',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
