# Generated by Django 4.0.2 on 2022-02-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0023_alter_lote_producto_alter_lote_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanque',
            options={'ordering': ['tag']},
        ),
    ]
