# Generated by Django 4.0.2 on 2022-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0027_lote_cliente_loteapi_cliente_alter_calculo_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculoapi',
            old_name='lote_api',
            new_name='lote',
        ),
        migrations.AlterField(
            model_name='calculo',
            name='estado',
            field=models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA'), ('ID', 'INICIAL DESPACHO'), ('IR', 'INICIAL RECIBO'), ('FD', 'FINAL DESPACHO'), ('FR', 'FINAL RECIBO'), ('T', 'TENTATIVA'), ('IT', 'INICIAL TRASLADO'), ('FT', 'FINAL TRASLADO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='calculoapi',
            name='estado',
            field=models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA'), ('ID', 'INICIAL DESPACHO'), ('IR', 'INICIAL RECIBO'), ('FD', 'FINAL DESPACHO'), ('FR', 'FINAL RECIBO'), ('T', 'TENTATIVA'), ('IT', 'INICIAL TRASLADO'), ('FT', 'FINAL TRASLADO')], max_length=2),
        ),
    ]
