# Generated by Django 4.0.2 on 2022-08-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0028_rename_lote_api_calculoapi_lote_alter_calculo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='do',
            field=models.IntegerField(blank=True, max_length=8, null=True, verbose_name='DO'),
        ),
        migrations.AlterField(
            model_name='calculo',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='bun.lote', verbose_name='Lote Siesa'),
        ),
    ]
