# Generated by Django 4.0.2 on 2022-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0029_calculo_do_alter_calculo_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='do',
            field=models.IntegerField(blank=True, null=True, verbose_name='DO'),
        ),
    ]
