# Generated by Django 4.0.2 on 2022-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun', '0030_alter_calculo_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoapi',
            name='do',
            field=models.IntegerField(blank=True, null=True, verbose_name='DO'),
        ),
    ]
