# Generated by Django 4.0.2 on 2022-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_calculopruebasbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotebar',
            name='producto',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='lotebar',
            name='referencia',
            field=models.CharField(max_length=50),
        ),
    ]
