# Generated by Django 4.0.2 on 2022-02-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_alter_lotebar_producto_alter_lotebar_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanquebar',
            options={'ordering': ['bodega']},
        ),
    ]
