# Generated by Django 4.0.2 on 2022-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_loteapibar_cliente_lotebar_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculoapibar',
            name='estado',
            field=models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA'), ('ID', 'INICIAL DESPACHO'), ('IR', 'INICIAL RECIBO'), ('FD', 'FINAL DESPACHO'), ('FR', 'FINAL RECIBO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='calculobar',
            name='estado',
            field=models.CharField(choices=[('F', 'FINAL'), ('I', 'INICIAL'), ('C', 'CONTROL'), ('D', 'DEFINITIVA'), ('ID', 'INICIAL DESPACHO'), ('IR', 'INICIAL RECIBO'), ('FD', 'FINAL DESPACHO'), ('FR', 'FINAL RECIBO')], max_length=2),
        ),
    ]
